from .home import home_bp
from .about import about_bp
from .certificate_achievement import certi_bp
from .contact import contact_bp
from .education import education_bp
from .experience import experience_bp
from .project import project_bp
from .resume import resume_bp
from .skills import skill_bp
